### ISSUE TITLE
Ideas para modulos extra 

### ISSUE THREAD

**Issue by terceranexus6** [iblancasa/hackathon_telefonica#5]
de led y sonido

**Comment by terceranexus6** [comment]
encender led cuando el valor de la luminosidad sea baja, para que el usuario encuentre el módulo con más facilidad en un entorno oscuro.

**Comment by terceranexus6** [comment]
encender el sonido en bucle mientras la sala esta en una temperatura peligrosa (tanto por encima como por debajo de lo normal)

**Comment by terceranexus6** [comment]
el string para el sonido es 3:1:1000:2Bs.N el primer numero indica la cantidad de pitidos. se pueden variar tanto el 3 como el 1 como el 1000. Se cambia en atributos:
{
    "attributes":[
        {
            "name": "color",
            "type": "string",
            "value": "1,1,0"
        },

```
    {
        "name": "melody",
        "type": "string",
        "value": "0"
    }
    ]
```

}

PARA EL COLOR indica los colores rgb red green blue, y pueden combinarse. Todo esto esta en post-body-raw

**Comment by iblancasa** [comment]
Hay que cambiar algunas cosas:
- Como url hay que poner la de "http://hackathon.ttcloud.telefonica.net:10026"
- En la cadena que se pasa al JSON.stringfy hay que poner lo que le quieras mandar al servidor (el código este que es un diccionario)
- Hay que pasarle los otros headers, igual que se le pasa en `xhr.setRequestHeader("Content-type", "application/json");`

``` javacript
xhr = new XMLHttpRequest();
var url = "url";
xhr.open("POST", url, true);
xhr.setRequestHeader("Content-type", "application/json");
xhr.onreadystatechange = function () { 
    if (xhr.readyState == 4 && xhr.status == 200) {
        var json = JSON.parse(xhr.responseText);
        console.log(json.email + ", " + json.password)
    }
}
var data = JSON.stringify({"email":"hey@mail.com","password":"101010"});
xhr.send(data);
```

**Comment by terceranexus6** [comment]
xhr = new XMLHttpRequest();
var url = "http://hackathon.ttcloud.net:10026/v1/contextEntities/type/thinkingthing/id/ZJ0SW7";
xhr.open("POST", url, true);
xhr.setRequestHeader("Content-type", "application/json");
xhr.setRequestHeader("Fiware-Service", "todosincluidos");
xhr.setRequestHeader("Fiware-ServicePath", "/iot");
xhr.setRequestHeader("Content-Type", "application/json");
xhr.setRequestHeader("Accept", "application/json");
xhr.onreadystatechange = function () { 
    if (xhr.readyState == 4 && xhr.status == 200) {
        var json = JSON.parse(xhr.responseText);
        console.log(json.email + ", " + json.password)
    }
}
var data = JSON.stringify({
    "attributes":[
        {
            "name": "color",
            "type": "string",
            "value": "1,0,0"
        },

```
    {
        "name": "melody",
        "type": "string",
        "value": "0"
    }
    ]
```

});
xhr.send(data);

**Comment by terceranexus6** [comment]
string de musica 3:2:1000:4Db.N:1Ds.N:2Ds.N:4Ds.N
